#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/glmasr/modular_glmasr.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_glmasr.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 the HuggingFace Team. All rights reserved.
#
# This code is adapted from https://github.com/huggingface/transformers
# with modifications to run transformers on mindspore.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
from typing import Optional, Union

import numpy as np

from ...audio_utils import AudioInput, make_list_of_audio
from ...feature_extraction_utils import BatchFeature
from ...processing_utils import ProcessingKwargs, ProcessorMixin, Unpack
from ...tokenization_utils_base import TextInput
from ...utils import is_mindspore_available, logging


if is_mindspore_available():
    import mindspore


logger = logging.get_logger(__name__)


class GlmAsrProcessorKwargs(ProcessingKwargs, total=False):
    _defaults = {
        "text_kwargs": {
            "padding": True,
        },
        "audio_kwargs": {
            "sampling_rate": 16000,
            "chunk_length": 30.0,
            "return_attention_mask": True,
            "padding": "max_length",
        },
        "common_kwargs": {
            "return_tensors": "ms",
            "padding_side": "left",
        },
    }


class GlmAsrProcessor(ProcessorMixin):
    r"""
    Constructs an GlmAsr processor which wraps an GlmAsr feature extractor and an GlmAsr
    tokenizer into a single processor.

    [`GlmAsrProcessor`] offers all the functionalities of [`WhisperFeatureExtractor`] and
    [`Qwen2TokenizerFast`]. See the [`~GlmAsrProcessor.__call__`] for more information.

    Args:
            feature_extractor ([`WhisperFeatureExtractor`]):
                The feature extractor is a required input.
            tokenizer ([`Qwen2TokenizerFast`]):
                The tokenizer is a required input.
            chat_template (`Optional[str]`, *optional*):
                The Jinja template to use for formatting the conversation. If not provided, the tokenizer's default chat
                template will be used.
            audio_token (`Optional[str]`, *optional*, defaults to `"<|pad|>`"):
                Special token used to represent audio inputs in the chat template.
            default_transcription_prompt (`str`, *optional*, defaults to `"Please transcribe this audio into text"`):
                Default prompt to use for transcription tasks when applying transcription requests.
            max_audio_len (`int`, *optional*, defaults to 655):
                Maximum length of audio sequences in seconds. Audio longer than this will be truncated.
                655 gives approximately 8192 tokens, corresponding to the maximum sequence length of the text model.
    """

    def __init__(
        self,
        feature_extractor,
        tokenizer,
        chat_template=None,
        audio_token="<|pad|>",
        default_transcription_prompt="Please transcribe this audio into text",
        max_audio_len=655,
    ):
        self.audio_token = audio_token
        self.audio_token_id = tokenizer.convert_tokens_to_ids(audio_token)
        self.default_transcription_prompt = default_transcription_prompt
        self.max_audio_len = max_audio_len
        super().__init__(feature_extractor, tokenizer, chat_template=chat_template)

    def _get_audio_token_length(self, audio_lengths: "mindspore.Tensor") -> "mindspore.Tensor":
        merge_factor = 4
        compress_ratio = 2.5

        # Reshape input based on merge_factor (default: 4 -> [batch_size, 4, seq_length//4])
        # then mean across 1st dim and get length excluding padding
        input_mel_lengths = audio_lengths // merge_factor

        # Calculate the expected output lengths from the time-compression-ratio
        audio_token_lengths = (input_mel_lengths / compress_ratio).to(mindspore.int64)

        return audio_token_lengths

    def __call__(
        self,
        text: Optional[Union[TextInput, list[TextInput], list[dict]]] = None,
        audio: Optional[AudioInput] = None,
        transcription_prompts: Optional[Union[str, list[str]]] = None,
        **kwargs: Unpack[GlmAsrProcessorKwargs],
    ) -> BatchFeature:
        """
        Main method to prepare for the model one or several sequences(s) and audio(s). This method forwards the `text`
        and `kwargs` arguments to Qwen2TokenizerFast's [`~Qwen2TokenizerFast.__call__`] if `text` is not `None` to encode
        the text. To prepare the audio(s), this method forwards the `audio` and `kwargs` arguments to
        WhisperFeatureExtractor's [`~WhisperFeatureExtractor.__call__`] if `audio` is not `None`. Please refer to the doctsring
        of the above two methods for more information.

        Args:
            text (`str`, `list[str]`, `list[dict]`):
                The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings
                (pretokenized string). If the sequences are provided as a list of strings (pretokenized), you must set
                `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).

                Whenever a conversation template or chat template is supported, passing a list of dict will unroll the conversation
                into a text sequence. The dicts need to have the keys "role" and "content", representing the speaker and the message.
            audio (`str`, `list[str]`, `np.ndarray`, `mindspore.Tensor`, `list[np.ndarray]`, `list[mindspore.Tensor]`):
                The audio or batch of audios to be prepared. Each audio can be NumPy array or MindSpore tensor. In case
                of a NumPy array/MindSpore tensor, each audio should be a mono or stereo audio of shape (n_samples,).

            transcription_prompts (`str`, *optional*, `list[str]`):
                Transcription prompts to be used for each audio in the batch. If not provided, the default transcription
                prompt will be used.

        Returns:
            [`BatchFeature`]: A [`BatchFeature`] with the following fields:

            - **input_features** -- Audio input features to be fed to a model. Returned when `audio` is not `None`.
            - **input_ids** -- List of token ids to be fed to a model. Returned when `text` is not `None`.
            - **attention_mask** -- List of indices specifying which tokens should be attended to by the model (when
              `return_attention_mask=True` or if *"attention_mask"* is in `self.model_input_names` and if `text` is not
              `None`).
        """
        output_kwargs = self._merge_kwargs(
            GlmAsrProcessorKwargs,
            tokenizer_init_kwargs=self.tokenizer.init_kwargs,
            **kwargs,
        )

        if transcription_prompts is not None:
            transcription_prompts = [transcription_prompts] if isinstance(transcription_prompts, str) else transcription_prompts

        # 1. check if we need to process the audio, and if yes, extract the features
        if audio is not None:
            audio_features = self._process_audio(audio=audio, **output_kwargs["audio_kwargs"])
        else:
            audio_features = None

        # 2. check if we need to process the text
        if isinstance(text, str):
            text = [text]
        elif not isinstance(text, list) and text is not None:
            raise ValueError("Invalid input text. Please provide a string, or a list of strings")

        # shortcut when using transcription mode
        if text is None:
            text = [self.default_transcription_prompt] * len(audio_features["input_features"])
            transcription_mode = True
        else:
            transcription_mode = False

        # Encode text
        text_features = self.tokenizer(text=text, **output_kwargs["text_kwargs"], **output_kwargs["common_kwargs"])

        if audio is not None:
            # 3. merge the text and audio features
            if isinstance(audio, str):
                audio_items: list[Union[str, np.ndarray]] = [audio]
            elif isinstance(audio, (list, tuple)) and audio and all(isinstance(el, str) for el in audio):
                audio_items = list(audio)
            else:
                audio_items = list(make_list_of_audio(audio))
                if is_mindspore_available():
                    audio_items = [el.asnumpy() if isinstance(el, mindspore.Tensor) else el for el in audio_items]

            num_audios_per_sample = [len(re.findall(re.escape(self.audio_token), s)) for s in text]
            num_audios_provided = len(audio_items)

            if transcription_mode and num_audios_provided == len(text):
                # If in transcription mode, accept audio matching the batch size
                pass
            elif sum(num_audios_per_sample) != num_audios_provided:
                raise ValueError(
                    f"The number of audio inputs ({num_audios_provided}) does not match the number of audio tokens in the text ({num_audios_per_sample})"
                )

            per_sample_windows = [a.shape[0] for a in audio_features["input_features"]]
            # Compute audio padding mask if needed
            if "attention_mask" in audio_features:
                padding_mask = audio_features["attention_mask"]
                audio_lengths = mindspore.Tensor([s.sum() for s in mindspore.mint.split(padding_mask.sum(-1), per_sample_windows)])
            else:
                audio_lengths = mindspore.Tensor([a.shape[-1] for a in audio_features["input_features"]])

            audio_token_lengths = self._get_audio_token_length(audio_lengths)

            if transcription_mode:
                # For transcription mode, prepend audio tokens to the beginning
                for idx, (sample_input_ids, audio_token_len) in enumerate(
                    zip(text_features["input_ids"], audio_token_lengths)
                ):
                    audio_ids = mindspore.Tensor([self.audio_token_id] * audio_token_len.item())
                    # Prepend audio tokens
                    text_features["input_ids"][idx] = mindspore.mint.cat([audio_ids, sample_input_ids])
            else:
                # For normal mode, replace audio tokens in text
                current_audio_idx = 0
                for idx, (sample_input_ids, num_audio_in_sample) in enumerate(zip(text_features["input_ids"], num_audios_per_sample)):
                    for _ in range(num_audio_in_sample):
                        audio_token_len = audio_token_lengths[current_audio_idx]
                        # Replace first occurrence of audio_token_id
                        audio_token_pos = (sample_input_ids == self.audio_token_id).nonzero()[0].item()
                        audio_ids = mindspore.Tensor([self.audio_token_id] * audio_token_len.item())

                        # Split and concatenate
                        before = sample_input_ids[:audio_token_pos]
                        after = sample_input_ids[audio_token_pos + 1 :]
                        sample_input_ids = mindspore.mint.cat([before, audio_ids, after])
                        current_audio_idx += 1

                    text_features["input_ids"][idx] = sample_input_ids

            # Re-pad and update attention mask
            text_features = self.tokenizer.pad(text_features, **output_kwargs["text_kwargs"], **output_kwargs["common_kwargs"])

        return BatchFeature(data={**text_features, **audio_features})

    def _process_audio(
        self,
        audio: AudioInput,
        **kwargs,
    ):
        """
        Processes audio inputs, including chunking long audio sequences and extracting features.

        Args:
            audio: Audio input which can be a file path, numpy array, or tensor.
            **kwargs: Additional arguments for the feature extractor.

        Returns:
            BatchFeature containing processed audio features and attention masks.
        """
        sampling_rate = kwargs.pop("sampling_rate", 16000)
        chunk_length = kwargs.pop("chunk_length", 30.0)

        if isinstance(audio, str):
            audio = [audio]
        elif not isinstance(audio, list):
            audio = [audio]

        # Process audio and extract features
        processed = self.feature_extractor(
            audio,
            sampling_rate=sampling_rate,
            chunk_length=chunk_length,
            **kwargs,
        )

        return processed

    def batch_decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to Qwen2TokenizerFast's [`~PreTrainedTokenizer.batch_decode`]. Please
        refer to the docstring of this method for more information.
        """
        return self.tokenizer.batch_decode(*args, **kwargs)

    def decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to Qwen2TokenizerFast's [`~PreTrainedTokenizer.decode`]. Please refer to
        the docstring of this method for more information.
        """
        return self.tokenizer.decode(*args, **kwargs)

    @property
    def model_input_names(self):
        tokenizer_input_names = self.tokenizer.model_input_names
        feature_extractor_input_names = self.feature_extractor.model_input_names
        return list(dict.fromkeys(tokenizer_input_names + feature_extractor_input_names))
